trigger:
- main

pool: 
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: NuGetToolInstaller@1
  displayName: 'NuGet Tool Installer'

- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'

- script: dotnet restore ClassLibrary1/ClassLibrary1.sln
  displayName: 'Restore dependencies'

- script: dotnet build ClassLibrary1/ClassLibrary1.sln --configuration Release
  displayName: 'Build project'

- script: dotnet test StringExtensionsLibrary.Tests/StringExtensionsLibrary.Tests..csproj --configuration Release
  displayName: 'Run tests'

- script: dotnet pack ClassLibrary1/StringExtensionsLibrary.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet Package'

- script: |
      nuget.exe push -Source "https://pkgs.dev.azure.com/lab-4/StringExtensionsLibraryProject/_packaging/MyNuGetFeed/nuget/v3/index.json" -ApiKey az $(Build.ArtifactStagingDirectory)\*.nupkg
  displayName: 'Publish to Azure Artifacts'