trigger:
- main

pool: 
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: NuGetToolInstaller@1
  displayName: 'NuGet Tool Installer'

- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'

- script: dotnet restore ClassLibrary1/ClassLibrary1.sln
  displayName: 'Restore dependencies'

- script: dotnet build ClassLibrary1/ClassLibrary1.sln --configuration Release
  displayName: 'Build project'

- script: dotnet test StringExtensionsLibrary.Tests/StringExtensionsLibrary.Tests..csproj --configuration Release
  displayName: 'Run tests'

# 🔥 Set auto-incrementing package version (Fix for extra quotes issue)
- script: |
    echo ##vso[task.setvariable variable=PackageVersion]1.0.$(Build.BuildId)
  displayName: 'Set Package Version'

# 🔥 Pack NuGet package with auto-incremented version
- script: dotnet pack ClassLibrary1/StringExtensionsLibrary.csproj --configuration Release --output $(Build.ArtifactStagingDirectory) /p:Version=$(PackageVersion)
  displayName: 'Pack NuGet Package'

# 🔥 Publish to Azure Artifacts
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)\*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'StringExtensionsLibraryProject/MyNuGetFeed'
  displayName: 'Publish to Azure Artifacts'
